-- 1. Asegurar que la tabla 'reports' existe
CREATE TABLE IF NOT EXISTS public.reports (
    id bigint generated by default as identity primary key,
    "fechaHora" text,
    "tipo" text,
    "origen" text,
    "sitioArea" text,
    "estado" text DEFAULT 'Pendiente',
    created_at timestamp with time zone default now()
);
-- 2. Asegurar que la columna 'detalles' existe (usando DO block para evitar error si ya existe)
DO $$ BEGIN IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'reports'
        AND column_name = 'detalles'
) THEN
ALTER TABLE public.reports
ADD COLUMN "detalles" jsonb;
END IF;
END $$;
-- 3. Permisos
GRANT ALL ON TABLE public.reports TO anon,
    authenticated,
    service_role;
-- 4. Habilitar tiempo real de forma segura
DO $$ BEGIN -- Solo intentar añadir si la tabla no está ya en la publicación
IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
        AND tablename = 'reports'
) THEN ALTER PUBLICATION supabase_realtime
ADD TABLE reports;
END IF;
END $$;
-- 5. Actualizar API Schema
NOTIFY pgrst,
'reload schema';