-- ==========================================
-- SCRIPT COMPLETO DEL SISTEMA DE VIGILANCIA
-- ==========================================
-- Este script crea/actualiza todas las tablas necesarias para la aplicación.
-- Incluye las correcciones para:
-- 1. Guardias (Campos extra: email, telefono, direccion, coordenadas)
-- 2. Reportes (JSONB 'detalles' para evidencia flexible)
-- 3. Entradas/Salidas (JSONB 'detalles' para fotos y notas)
-- 4. Tablas base (Admins, Cameras, Buildings)
-- Habilitar extensión UUID (necesaria para IDs únicos)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- ==========================================
-- 1. TABLA ADMINS
-- ==========================================
CREATE TABLE IF NOT EXISTS public.admins (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    "fullName" text,
    email text UNIQUE NOT NULL,
    password text NOT NULL,
    -- Nota: En producción, usar hashing
    "companyName" text,
    location text,
    lat double precision,
    lng double precision,
    zone jsonb,
    -- Coordenadas del polígono de la zona
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);
-- ==========================================
-- 2. TABLA GUARDS (Actualizada)
-- ==========================================
-- Se recrea o asegura con los campos necesarios para la App Móvil y Web
CREATE TABLE IF NOT EXISTS public.guards (
    "idEmpleado" text PRIMARY KEY,
    "nombre" text NOT NULL,
    "email" text,
    "telefono" text,
    "direccion" text,
    "foto" text,
    "area" text,
    "estado" text DEFAULT 'Fuera de servicio',
    "lat" float8,
    "lng" float8,
    "fechaContratacion" timestamp with time zone DEFAULT now(),
    -- Campos legado o extra que puedan ser útiles
    actividades jsonb DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);
-- Permisos rápidos para desarrollo
GRANT ALL ON TABLE public.guards TO anon,
    authenticated,
    service_role;
-- ==========================================
-- 3. TABLA CAMERAS
-- ==========================================
CREATE TABLE IF NOT EXISTS public.cameras (
    id text PRIMARY KEY,
    -- Ejemplo: "CAM-001"
    ip text,
    marca text,
    modelo text,
    activa boolean DEFAULT true,
    area text,
    alertas int DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);
-- ==========================================
-- 4. TABLA REPORTS (Reportes/Alertas)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.reports (
    id bigint generated by default as identity primary key,
    "fechaHora" text,
    -- ISO String desde la app
    "tipo" text,
    "origen" text,
    "sitioArea" text,
    "estado" text DEFAULT 'Pendiente',
    created_at timestamp with time zone default now()
);
-- Asegurar columna flexible 'detalles' (Para evidencia, descripciones largas, etc.)
DO $$ BEGIN IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'reports'
        AND column_name = 'detalles'
) THEN
ALTER TABLE public.reports
ADD COLUMN "detalles" jsonb;
END IF;
END $$;
-- Permisos
GRANT ALL ON TABLE public.reports TO anon,
    authenticated,
    service_role;
-- Habilitar tiempo real de forma segura
DO $$ BEGIN IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
        AND tablename = 'reports'
) THEN ALTER PUBLICATION supabase_realtime
ADD TABLE reports;
END IF;
END $$;
-- ==========================================
-- 5. TABLA BUILDINGS (Edificios/Sitios)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.buildings (
    id text PRIMARY KEY,
    name text,
    geometry jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);
-- ==========================================
-- 6. TABLA ENTRIES_EXITS (Entradas y Salidas)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.entries_exits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "fechaHora" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    tipo TEXT NOT NULL,
    -- 'Entrada' o 'Salida'
    descripcion TEXT,
    "idRelacionado" text,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
-- Asegurar columna 'detalles' para las fotos de evidencia
DO $$ BEGIN IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'entries_exits'
        AND column_name = 'detalles'
) THEN
ALTER TABLE public.entries_exits
ADD COLUMN "detalles" JSONB DEFAULT '{}'::jsonb;
END IF;
END $$;
-- Políticas de Seguridad (RLS) - Permisivas para desarrollo
ALTER TABLE public.entries_exits ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE tablename = 'entries_exits'
        AND policyname = 'Allow anonymous insert'
) THEN CREATE POLICY "Allow anonymous insert" ON public.entries_exits FOR
INSERT TO anon WITH CHECK (true);
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE tablename = 'entries_exits'
        AND policyname = 'Allow anonymous select'
) THEN CREATE POLICY "Allow anonymous select" ON public.entries_exits FOR
SELECT TO anon USING (true);
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE tablename = 'entries_exits'
        AND policyname = 'Allow anonymous update'
) THEN CREATE POLICY "Allow anonymous update" ON public.entries_exits FOR
UPDATE TO anon USING (true);
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE tablename = 'entries_exits'
        AND policyname = 'Allow anonymous delete'
) THEN CREATE POLICY "Allow anonymous delete" ON public.entries_exits FOR DELETE TO anon USING (true);
END IF;
END $$;
-- ==========================================
-- 7. ACTUALIZAR CACHÉ DE API
-- ==========================================
NOTIFY pgrst,
'reload schema';